import jwt
from datetime import datetime, timedelta, timezone


class JWTTokenService:
    def __init__(self, secret_token) -> None:
        self.secret_token = secret_token

    def generate(self, user_uuid: str) -> str:
        payload = {
            "u": user_uuid,
            "exp": datetime.now(timezone.utc) + timedelta(hours=1),
        }
        jwt_token = jwt.encode(payload, self.secret_token, algorithm="HS256")
        return jwt_token

    def verify(self, token: str) -> dict:
        """
        This will verify if both the token was generated by this backend and if its not expired.
        """
        jwt_payload = jwt.decode(token, self.secret_token, algorithms=["HS256"])
        if jwt_payload.get("exp", datetime.now()) <= datetime.now():
            raise Exception("Expired Token")  # TODO add proper Exception
        return jwt_payload
