def test_deposit_happy_path(): ...

def test_deposit_negative_value(): ...

def test_deposit_zero_value(): ...

def test_deposit_with_bank_with_is_external_managed_false_and_amount_over(): ...

def test_deposit_with_bank_with_is_external_managed_and_amount_over(): ...


def test_withdraw_happy_path():...

def test_withdraw_negative_value(): ...

def test_withdraw_zero_value(): ...

def test_withdraw_with_bank_with_is_external_managed_false_and_amount_over(): ...

def test_withdraw_with_is_external_managed_true_and_amount_over(): ...


def test_transfer_happy_path():...

def test_transfer_negative_value(): ...

def test_transfer_zero_value(): ...

def test_transfer_with_bank_with_is_external_managed_false_and_amount_over(): ...

def test_transfer_with_is_external_managed_true_and_amount_over(): ...