from typing import Protocol

from .entities import User


class UserRepository(Protocol):
    def save(self, user: User) -> bool: ...
    def get(self, uuid: str) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def update(self, uuid: str, user: User) -> User | None: ...
    def delete(self, uuid: str) -> bool: ...
