"""initial migration

Revision ID: 45d57f89ec54
Revises:
Create Date: 2026-04-13 17:26:08.697984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45d57f89ec54"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "transactions",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )

    op.create_table(
        "wallets",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=False)

    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_id", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Numeric(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["currencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exchange_rates_base_id"), "exchange_rates", ["base_id"], unique=False
    )
    op.create_index(
        op.f("ix_exchange_rates_quote_id"), "exchange_rates", ["quote_id"], unique=False
    )
    op.create_table(
        "wallet_transaction_snapshot",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("wallet_uuid", sa.String(length=36), nullable=False),
        sa.Column("transaction_uuid", sa.String(length=36), nullable=False),
        sa.Column("projected_balance", sa.Integer(), nullable=False),
        sa.Column("projected_currency_id", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_start_datetime", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("snapshot_end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["projected_currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_uuid"],
            ["transactions.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_uuid"],
            ["wallets.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallet_transaction_snapshot")
    op.drop_index(op.f("ix_exchange_rates_quote_id"), table_name="exchange_rates")
    op.drop_index(op.f("ix_exchange_rates_base_id"), table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_table("transactions")
    op.drop_table("currencies")
    # ### end Alembic commands ###
