from typing import Protocol

from .entities import Wallet, WalletSnapshot


class WalletRepository(Protocol):
    def get_by_id(self, uuid: str) -> Wallet: ...
    def save(self, wallet: Wallet) -> bool: ...


class WalletSnapshotRepository(Protocol):
    def get_by_wallet_id(self, wallet_id) -> list[WalletSnapshot]: ...
    def get_latest_by_wallet_id(self, wallet_id: str) -> WalletSnapshot: ...
